# Let us also create a 3rd role called Python to install Python and its dependencies.
# A command has been run to create a new role called python and the required files are in place. Check out the folder structure.
# Now move the first task to "Install dependencies" into "roles/python/tasks/main.yml" file.
# Remove the "tasks" directive from the play and leave it empty.
# Note: We will add roles statement in a later Exercise
#
#
## ------------------------------
##           BEFORE
## ------------------------------
#-
#  name: Deploy a web application
#  hosts: db_and_web_server
#  tasks:
#    - name: Install dependencies
#      apt: name={{ item }} state=installed
#      with_items:
#       - python
#       - python-setuptools
#       - python-dev
#       - build-essential
#       - python-pip
#       - python-mysqldb

# ------------------------------
#           AFTER
# ------------------------------
-
  name: Deploy a web application
  hosts: db_and_web_server



